### ISSUE TITLE
Incorrect calculations

### ISSUE THREAD

**Issue by ankycooper** [gurbyz/power-wheel-card#27]
I have read the wiki about what to try first before creating a bug report.

**Which custom card does give you issues?**
power-wheel-card

**Which version of HA do you use?**
100.2
**Which version of the card do you use?**
0.0.15
**Describe the bug**
the calculation seems skewed: at the moment I'm not producing any energy as the sun is down.
Power flow to grid value from my inverter: 556w (energy drawn from the grid)
Power flow load value from my inverter: -556w (energy consumed)

**Configuration of the card**

```
- platform: template
  sensors:
    solar_power:
      friendly_name: 'Solar power production'
      unit_of_measurement: 'W'
      value_template: >-
        {% if is_state('sensor.power_photovoltaics_fronius_power_flow_0_http_10_20_20_58', 'unknown') %}
        0
        {% else %}
        {{ states("sensor.power_photovoltaics_fronius_power_flow_0_http_10_20_20_58" | float) | int }}
        {% endif %}
    power_consumption:
      friendly_name: 'Power Consumption'
      unit_of_measurement: 'W'
      value_template: >-
        {{  states("sensor.power_load_fronius_power_flow_0_http_10_20_20_58")  }}

    power_exported:
      friendly_name: 'Power Exported'
      unit_of_measurement: 'W'
      value_template: >-
        {{ states("sensor.power_grid_fronius_power_flow_0_http_10_20_20_58") }}

```

**Expected behaviour**
the arrow should point in the direction of energy flow and fix the calculations

**Screenshots**
![image](https://user-images.githubusercontent.com/20620956/67785301-15082c00-fac1-11e9-8164-fa9c57061c73.png)

**Comment by gurbyz** [comment]
Looks like you're feeding the card with two input sensors with same value. Can you share your card setup so I can check what parameters you are using? Look for `- type: "custom:power-wheel-card"` somewhere in your files and please share the code that's below it.

**Comment by ankycooper** [comment]
```
views:
  - cards:
      - grid_power_consumption_entity: sensor.power_load_fronius_power_flow_0_http_10_20_20_58
        grid_power_production_entity: sensor.power_grid_fronius_power_flow_0_http_10_20_20_58
        solar_power_entity: sensor.power_photovoltaics_fronius_power_flow_0_http_10_20_20_58
        type: 'custom:power-wheel-card'
    id: solar
```
