### ISSUE TITLE
Demand Tariff Support (Time of use)

### ISSUE THREAD

**Issue by trankillity** [gurbyz/power-wheel-card#56]
I understand that the money view currently doesn't support having variable tariffs based on time of use, but would like to propose a design solution for allowing it to do so.

I don't have that much programming experience, but here's how I'd envisage it in my head. The logic should check if `energy_consumption_rate` or `energy_production_rate` are List/Dict types. If they are, it should look for the `rate` and `start_time` variables under each. You shouldn't need an `end_time` variable as the logic should fill in the blanks for periods sorted by time.

An example of the adapted configuration would be:
```
energy_consumption_rate:
  - rate: 0.2233
    time_start: '07:00:00'
  - rate: 0.3625
    time_start: '16:00:00'
  - rate: 0.2233
    time_start: '20:00:00'
  - rate: 0.2013
    time_start: '22:00:00'
```
So this would equate to:
- 22.33c/kWh from 7:00am to 3:59pm
- 36.25c/kWh from 4:00pm to 7:59pm
- 22.33c/kWh from 8:00pm to 9:59pm
- 20.13c/kWh from 10:00pm to 6:59am

This could even be extended to allow for day-of-week tariffs in a similar way, as my area has different tariffs on the weekend than it does on the week day.
