### ISSUE TITLE
Attribute Support Help

### ISSUE THREAD

**Issue by tet024** [gurbyz/power-wheel-card#83]
Hello, 

For the solar_power_entity I have an Attribute within the entity how can i configure that  please. Basically for all the required entities I have one Entity then they are all sub attributes to that entity. 

Help would be greatly appreciated. 

Thanks, 
Etienne

**Comment by gurbyz** [comment]
You can convert attributes of entities to their own entities using *template sensors*. In this way you can create a new sensor entity that is based on one of the attributes of another entity.

Here's an example of such a sensor created in yaml specification:
```
sensor:
  - platform: template
    sensors:
      this_is_my_new_entity:
        friendly_name: 'My beautiful entity'
        unit_of_measurement: 'kW'
        value_template: >-
          {{ state_attr("climate.my_old_entity", "the_name_of_the_attribute") }}

```
Pls try to find more help on *template sensors* in the documentation of Home Assistant or on the forum of Home Assistant.
